/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.netflix.ads;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AdEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1999970346575887323L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AdEvent\",\"namespace\":\"com.netflix.ads\",\"fields\":[{\"name\":\"event_id\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"user_id\",\"type\":\"string\"},{\"name\":\"campaign_id\",\"type\":\"string\"},{\"name\":\"advertiser_id\",\"type\":\"string\"},{\"name\":\"country_code\",\"type\":\"string\"},{\"name\":\"bid_price\",\"type\":\"double\"},{\"name\":\"ad_format\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AdEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AdEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AdEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AdEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AdEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AdEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AdEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AdEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AdEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence event_id;
  private long timestamp;
  private java.lang.CharSequence user_id;
  private java.lang.CharSequence campaign_id;
  private java.lang.CharSequence advertiser_id;
  private java.lang.CharSequence country_code;
  private double bid_price;
  private java.lang.CharSequence ad_format;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AdEvent() {}

  /**
   * All-args constructor.
   * @param event_id The new value for event_id
   * @param timestamp The new value for timestamp
   * @param user_id The new value for user_id
   * @param campaign_id The new value for campaign_id
   * @param advertiser_id The new value for advertiser_id
   * @param country_code The new value for country_code
   * @param bid_price The new value for bid_price
   * @param ad_format The new value for ad_format
   */
  public AdEvent(java.lang.CharSequence event_id, java.lang.Long timestamp, java.lang.CharSequence user_id, java.lang.CharSequence campaign_id, java.lang.CharSequence advertiser_id, java.lang.CharSequence country_code, java.lang.Double bid_price, java.lang.CharSequence ad_format) {
    this.event_id = event_id;
    this.timestamp = timestamp;
    this.user_id = user_id;
    this.campaign_id = campaign_id;
    this.advertiser_id = advertiser_id;
    this.country_code = country_code;
    this.bid_price = bid_price;
    this.ad_format = ad_format;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return event_id;
    case 1: return timestamp;
    case 2: return user_id;
    case 3: return campaign_id;
    case 4: return advertiser_id;
    case 5: return country_code;
    case 6: return bid_price;
    case 7: return ad_format;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: event_id = (java.lang.CharSequence)value$; break;
    case 1: timestamp = (java.lang.Long)value$; break;
    case 2: user_id = (java.lang.CharSequence)value$; break;
    case 3: campaign_id = (java.lang.CharSequence)value$; break;
    case 4: advertiser_id = (java.lang.CharSequence)value$; break;
    case 5: country_code = (java.lang.CharSequence)value$; break;
    case 6: bid_price = (java.lang.Double)value$; break;
    case 7: ad_format = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'event_id' field.
   * @return The value of the 'event_id' field.
   */
  public java.lang.CharSequence getEventId() {
    return event_id;
  }


  /**
   * Sets the value of the 'event_id' field.
   * @param value the value to set.
   */
  public void setEventId(java.lang.CharSequence value) {
    this.event_id = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'user_id' field.
   * @return The value of the 'user_id' field.
   */
  public java.lang.CharSequence getUserId() {
    return user_id;
  }


  /**
   * Sets the value of the 'user_id' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.CharSequence value) {
    this.user_id = value;
  }

  /**
   * Gets the value of the 'campaign_id' field.
   * @return The value of the 'campaign_id' field.
   */
  public java.lang.CharSequence getCampaignId() {
    return campaign_id;
  }


  /**
   * Sets the value of the 'campaign_id' field.
   * @param value the value to set.
   */
  public void setCampaignId(java.lang.CharSequence value) {
    this.campaign_id = value;
  }

  /**
   * Gets the value of the 'advertiser_id' field.
   * @return The value of the 'advertiser_id' field.
   */
  public java.lang.CharSequence getAdvertiserId() {
    return advertiser_id;
  }


  /**
   * Sets the value of the 'advertiser_id' field.
   * @param value the value to set.
   */
  public void setAdvertiserId(java.lang.CharSequence value) {
    this.advertiser_id = value;
  }

  /**
   * Gets the value of the 'country_code' field.
   * @return The value of the 'country_code' field.
   */
  public java.lang.CharSequence getCountryCode() {
    return country_code;
  }


  /**
   * Sets the value of the 'country_code' field.
   * @param value the value to set.
   */
  public void setCountryCode(java.lang.CharSequence value) {
    this.country_code = value;
  }

  /**
   * Gets the value of the 'bid_price' field.
   * @return The value of the 'bid_price' field.
   */
  public double getBidPrice() {
    return bid_price;
  }


  /**
   * Sets the value of the 'bid_price' field.
   * @param value the value to set.
   */
  public void setBidPrice(double value) {
    this.bid_price = value;
  }

  /**
   * Gets the value of the 'ad_format' field.
   * @return The value of the 'ad_format' field.
   */
  public java.lang.CharSequence getAdFormat() {
    return ad_format;
  }


  /**
   * Sets the value of the 'ad_format' field.
   * @param value the value to set.
   */
  public void setAdFormat(java.lang.CharSequence value) {
    this.ad_format = value;
  }

  /**
   * Creates a new AdEvent RecordBuilder.
   * @return A new AdEvent RecordBuilder
   */
  public static com.netflix.ads.AdEvent.Builder newBuilder() {
    return new com.netflix.ads.AdEvent.Builder();
  }

  /**
   * Creates a new AdEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AdEvent RecordBuilder
   */
  public static com.netflix.ads.AdEvent.Builder newBuilder(com.netflix.ads.AdEvent.Builder other) {
    if (other == null) {
      return new com.netflix.ads.AdEvent.Builder();
    } else {
      return new com.netflix.ads.AdEvent.Builder(other);
    }
  }

  /**
   * Creates a new AdEvent RecordBuilder by copying an existing AdEvent instance.
   * @param other The existing instance to copy.
   * @return A new AdEvent RecordBuilder
   */
  public static com.netflix.ads.AdEvent.Builder newBuilder(com.netflix.ads.AdEvent other) {
    if (other == null) {
      return new com.netflix.ads.AdEvent.Builder();
    } else {
      return new com.netflix.ads.AdEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for AdEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AdEvent>
    implements org.apache.avro.data.RecordBuilder<AdEvent> {

    private java.lang.CharSequence event_id;
    private long timestamp;
    private java.lang.CharSequence user_id;
    private java.lang.CharSequence campaign_id;
    private java.lang.CharSequence advertiser_id;
    private java.lang.CharSequence country_code;
    private double bid_price;
    private java.lang.CharSequence ad_format;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.netflix.ads.AdEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.event_id)) {
        this.event_id = data().deepCopy(fields()[0].schema(), other.event_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.user_id)) {
        this.user_id = data().deepCopy(fields()[2].schema(), other.user_id);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.campaign_id)) {
        this.campaign_id = data().deepCopy(fields()[3].schema(), other.campaign_id);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.advertiser_id)) {
        this.advertiser_id = data().deepCopy(fields()[4].schema(), other.advertiser_id);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.country_code)) {
        this.country_code = data().deepCopy(fields()[5].schema(), other.country_code);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.bid_price)) {
        this.bid_price = data().deepCopy(fields()[6].schema(), other.bid_price);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.ad_format)) {
        this.ad_format = data().deepCopy(fields()[7].schema(), other.ad_format);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing AdEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.netflix.ads.AdEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.event_id)) {
        this.event_id = data().deepCopy(fields()[0].schema(), other.event_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.user_id)) {
        this.user_id = data().deepCopy(fields()[2].schema(), other.user_id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.campaign_id)) {
        this.campaign_id = data().deepCopy(fields()[3].schema(), other.campaign_id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.advertiser_id)) {
        this.advertiser_id = data().deepCopy(fields()[4].schema(), other.advertiser_id);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.country_code)) {
        this.country_code = data().deepCopy(fields()[5].schema(), other.country_code);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.bid_price)) {
        this.bid_price = data().deepCopy(fields()[6].schema(), other.bid_price);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.ad_format)) {
        this.ad_format = data().deepCopy(fields()[7].schema(), other.ad_format);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'event_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getEventId() {
      return event_id;
    }


    /**
      * Sets the value of the 'event_id' field.
      * @param value The value of 'event_id'.
      * @return This builder.
      */
    public com.netflix.ads.AdEvent.Builder setEventId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.event_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'event_id' field has been set.
      * @return True if the 'event_id' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'event_id' field.
      * @return This builder.
      */
    public com.netflix.ads.AdEvent.Builder clearEventId() {
      event_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.netflix.ads.AdEvent.Builder setTimestamp(long value) {
      validate(fields()[1], value);
      this.timestamp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.netflix.ads.AdEvent.Builder clearTimestamp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'user_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserId() {
      return user_id;
    }


    /**
      * Sets the value of the 'user_id' field.
      * @param value The value of 'user_id'.
      * @return This builder.
      */
    public com.netflix.ads.AdEvent.Builder setUserId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.user_id = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'user_id' field has been set.
      * @return True if the 'user_id' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'user_id' field.
      * @return This builder.
      */
    public com.netflix.ads.AdEvent.Builder clearUserId() {
      user_id = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'campaign_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getCampaignId() {
      return campaign_id;
    }


    /**
      * Sets the value of the 'campaign_id' field.
      * @param value The value of 'campaign_id'.
      * @return This builder.
      */
    public com.netflix.ads.AdEvent.Builder setCampaignId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.campaign_id = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'campaign_id' field has been set.
      * @return True if the 'campaign_id' field has been set, false otherwise.
      */
    public boolean hasCampaignId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'campaign_id' field.
      * @return This builder.
      */
    public com.netflix.ads.AdEvent.Builder clearCampaignId() {
      campaign_id = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'advertiser_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getAdvertiserId() {
      return advertiser_id;
    }


    /**
      * Sets the value of the 'advertiser_id' field.
      * @param value The value of 'advertiser_id'.
      * @return This builder.
      */
    public com.netflix.ads.AdEvent.Builder setAdvertiserId(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.advertiser_id = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'advertiser_id' field has been set.
      * @return True if the 'advertiser_id' field has been set, false otherwise.
      */
    public boolean hasAdvertiserId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'advertiser_id' field.
      * @return This builder.
      */
    public com.netflix.ads.AdEvent.Builder clearAdvertiserId() {
      advertiser_id = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'country_code' field.
      * @return The value.
      */
    public java.lang.CharSequence getCountryCode() {
      return country_code;
    }


    /**
      * Sets the value of the 'country_code' field.
      * @param value The value of 'country_code'.
      * @return This builder.
      */
    public com.netflix.ads.AdEvent.Builder setCountryCode(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.country_code = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'country_code' field has been set.
      * @return True if the 'country_code' field has been set, false otherwise.
      */
    public boolean hasCountryCode() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'country_code' field.
      * @return This builder.
      */
    public com.netflix.ads.AdEvent.Builder clearCountryCode() {
      country_code = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'bid_price' field.
      * @return The value.
      */
    public double getBidPrice() {
      return bid_price;
    }


    /**
      * Sets the value of the 'bid_price' field.
      * @param value The value of 'bid_price'.
      * @return This builder.
      */
    public com.netflix.ads.AdEvent.Builder setBidPrice(double value) {
      validate(fields()[6], value);
      this.bid_price = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'bid_price' field has been set.
      * @return True if the 'bid_price' field has been set, false otherwise.
      */
    public boolean hasBidPrice() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'bid_price' field.
      * @return This builder.
      */
    public com.netflix.ads.AdEvent.Builder clearBidPrice() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'ad_format' field.
      * @return The value.
      */
    public java.lang.CharSequence getAdFormat() {
      return ad_format;
    }


    /**
      * Sets the value of the 'ad_format' field.
      * @param value The value of 'ad_format'.
      * @return This builder.
      */
    public com.netflix.ads.AdEvent.Builder setAdFormat(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.ad_format = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'ad_format' field has been set.
      * @return True if the 'ad_format' field has been set, false otherwise.
      */
    public boolean hasAdFormat() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'ad_format' field.
      * @return This builder.
      */
    public com.netflix.ads.AdEvent.Builder clearAdFormat() {
      ad_format = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AdEvent build() {
      try {
        AdEvent record = new AdEvent();
        record.event_id = fieldSetFlags()[0] ? this.event_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.timestamp = fieldSetFlags()[1] ? this.timestamp : (java.lang.Long) defaultValue(fields()[1]);
        record.user_id = fieldSetFlags()[2] ? this.user_id : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.campaign_id = fieldSetFlags()[3] ? this.campaign_id : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.advertiser_id = fieldSetFlags()[4] ? this.advertiser_id : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.country_code = fieldSetFlags()[5] ? this.country_code : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.bid_price = fieldSetFlags()[6] ? this.bid_price : (java.lang.Double) defaultValue(fields()[6]);
        record.ad_format = fieldSetFlags()[7] ? this.ad_format : (java.lang.CharSequence) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AdEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<AdEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AdEvent>
    READER$ = (org.apache.avro.io.DatumReader<AdEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.event_id);

    out.writeLong(this.timestamp);

    out.writeString(this.user_id);

    out.writeString(this.campaign_id);

    out.writeString(this.advertiser_id);

    out.writeString(this.country_code);

    out.writeDouble(this.bid_price);

    out.writeString(this.ad_format);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.event_id = in.readString(this.event_id instanceof Utf8 ? (Utf8)this.event_id : null);

      this.timestamp = in.readLong();

      this.user_id = in.readString(this.user_id instanceof Utf8 ? (Utf8)this.user_id : null);

      this.campaign_id = in.readString(this.campaign_id instanceof Utf8 ? (Utf8)this.campaign_id : null);

      this.advertiser_id = in.readString(this.advertiser_id instanceof Utf8 ? (Utf8)this.advertiser_id : null);

      this.country_code = in.readString(this.country_code instanceof Utf8 ? (Utf8)this.country_code : null);

      this.bid_price = in.readDouble();

      this.ad_format = in.readString(this.ad_format instanceof Utf8 ? (Utf8)this.ad_format : null);

    } else {
      for (int i = 0; i < 8; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.event_id = in.readString(this.event_id instanceof Utf8 ? (Utf8)this.event_id : null);
          break;

        case 1:
          this.timestamp = in.readLong();
          break;

        case 2:
          this.user_id = in.readString(this.user_id instanceof Utf8 ? (Utf8)this.user_id : null);
          break;

        case 3:
          this.campaign_id = in.readString(this.campaign_id instanceof Utf8 ? (Utf8)this.campaign_id : null);
          break;

        case 4:
          this.advertiser_id = in.readString(this.advertiser_id instanceof Utf8 ? (Utf8)this.advertiser_id : null);
          break;

        case 5:
          this.country_code = in.readString(this.country_code instanceof Utf8 ? (Utf8)this.country_code : null);
          break;

        case 6:
          this.bid_price = in.readDouble();
          break;

        case 7:
          this.ad_format = in.readString(this.ad_format instanceof Utf8 ? (Utf8)this.ad_format : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










